In [1]:
import tensorflow as tf

In [2]:
c1 = tf.constant([10, 20, 30, 40,50])

In [3]:
c1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([10, 20, 30, 40, 50])>

In [4]:
print(c1)

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)


In [5]:
tf.print(c1)

[10 20 30 40 50]


We can create a tf with:
- Variable
- Values
- List
- Numpy
- DataFrame
- Series  

All the Data should be of same datatype

In [6]:
list1 = ["apple", "orange", "Banana", "Kiwi"]

In [7]:
list1

['apple', 'orange', 'Banana', 'Kiwi']

In [8]:
type(list1)

list

In [9]:
c2 = tf.constant(list1)

In [10]:
c2

<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'apple', b'orange', b'Banana', b'Kiwi'], dtype=object)>

In [11]:
a = 100
b = 200
c = 300
d = 400

In [12]:
tf.constant([a, b, c, d])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([100, 200, 300, 400])>

In [13]:
import numpy as np

In [14]:
ary1 = np.arange(10, 16)

In [15]:
ary1

array([10, 11, 12, 13, 14, 15])

In [16]:
tf.constant([ary1])

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[10, 11, 12, 13, 14, 15]])>

In [17]:
tf.constant(np.arange(1,6))

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

Tensorflow don't take the dictionary directly, we've to convert to DataFrame

In [18]:
d1 = {
    "A": [10, 100, 1000],
    "B": [20, 200, 2000],
    "C": [30, 300, 3000],
    "D": [40, 400, 4000]
}

In [19]:
tf.constant(d1)

ValueError: Attempt to convert a value ({'A': [10, 100, 1000], 'B': [20, 200, 2000], 'C': [30, 300, 3000], 'D': [40, 400, 4000]}) with an unsupported type (<class 'dict'>) to a Tensor.

In [20]:
import pandas as pd

In [21]:
pd.DataFrame(d1, index = [0])

ValueError: Length of values (3) does not match length of index (1)

In [22]:
df1 = pd.DataFrame(d1)

In [23]:
df1

A     B     C     D
0    10    20    30    40
1   100   200   300   400
2  1000  2000  3000  4000

In [24]:
c2 = tf.constant(df1)

In [25]:
c2

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[  10,   20,   30,   40],
       [ 100,  200,  300,  400],
       [1000, 2000, 3000, 4000]], dtype=int64)>

### Attributes
Same as NumPy

In [26]:
c2.shape

TensorShape([3, 4])

In [27]:
c2.ndim

2

In [28]:
c2.dtype

tf.int64

In [29]:
c2.size

AttributeError: EagerTensor object has no attribute 'size'. 
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()
      

### Dummy Tensors

In [30]:
tf.zeros((3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [31]:
tf.zeros((3, 4), dtype = tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [32]:
tf.ones((4, 5), dtype = tf.int32)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])>

In [33]:
tf.ones((4, 5), dtype = "int16")

<tf.Tensor: shape=(4, 5), dtype=int16, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)>

In [34]:
tf.eye(4,4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Operations

##### Arithmetic Operations

In [35]:
tf1 = tf.constant([10, 20, 30, 40, 50])

In [36]:
tf1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([10, 20, 30, 40, 50])>

In [37]:
tf2 = tf.constant([100, 200,300, 400, 500])

In [38]:
tf1 + tf2

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([110, 220, 330, 440, 550])>

In [39]:
list1 = [10, 20, 30, 40, 50]

In [40]:
list2 = [100, 200, 300, 400, 500]

In [41]:
list1 + list2

[10, 20, 30, 40, 50, 100, 200, 300, 400, 500]

In [42]:
for i in list1:
    for j in list2:
        print(i+j)

110
210
310
410
510
120
220
320
420
520
130
230
330
430
530
140
240
340
440
540
150
250
350
450
550


In [43]:
for i in range(len(list1)):
    print(list1[i]+list2[i])

110
220
330
440
550


In [44]:
for x, y in zip(list1, list2):
    print(x+y)

110
220
330
440
550


In [45]:
tf1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([10, 20, 30, 40, 50])>

In [46]:
tf2

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([100, 200, 300, 400, 500])>

In [47]:
tf1 + tf2

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([110, 220, 330, 440, 550])>

In [48]:
tf2 - tf1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 90, 180, 270, 360, 450])>

In [49]:
"""
Element by Element Multiplication
"""
tf1*tf2

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 1000,  4000,  9000, 16000, 25000])>

In [50]:
tf2/tf1

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([10., 10., 10., 10., 10.])>

In [51]:
tf.add(tf1, tf2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([110, 220, 330, 440, 550])>

In [52]:
tf.subtract(tf2, tf1)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 90, 180, 270, 360, 450])>

In [53]:
tf.multiply(tf1, tf2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 1000,  4000,  9000, 16000, 25000])>

In [54]:
tf.divide(tf1, tf2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0.1, 0.1, 0.1, 0.1, 0.1])>

In [55]:
# tf.floor(tf2, tf1)

### Indexing and Slicing

In [56]:
tf.constant(np.arange(1, 10))

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [57]:
c3 = tf.constant(np.arange(1, 10), shape=(3,3))

In [58]:
tf.print(c3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
c4 = tf.constant(np.arange(11, 20), shape=(3,3))

In [60]:
tf.print(c4)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [61]:
c3 + c4

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])>

In [62]:
c3 * c4

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])>

In [63]:
# Matrix Multiplication
# row of m1 = col of m2
tf.matmul(c3, c4)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])>

In [64]:
cary1 = tf.constant(np.random.randint(10, 50, (4,6)))

In [65]:
cary1

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[23, 30, 30, 39, 45, 12],
       [23, 18, 24, 43, 47, 12],
       [33, 26, 16, 13, 36, 39],
       [24, 11, 12, 19, 32, 24]])>

In [66]:
# Slicing [columns, rows]
cary1[:, 2:4]

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[30, 39],
       [24, 43],
       [16, 13],
       [12, 19]])>

In [67]:
cary1[1,2]

<tf.Tensor: shape=(), dtype=int32, numpy=24>

### Important Functions
- ARGMAX
- ARGMIN

#### 

In [68]:
tf1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([10, 20, 30, 40, 50])>

In [69]:
tf3 = tf.constant(np.random.randint(10, 100, (10)))

In [70]:
tf3

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([40, 10, 34, 62, 54, 35, 76, 99, 18, 48])>

In [71]:
## ARGMAX: Find the max value
tf.argmax(tf3)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [72]:
# This gives us the index no of the max number

In [73]:
from tensorflow.keras.models import Sequential

In [74]:
from tensorflow.keras.layers import Flatten, Dense